<?xml version="1.0" encoding="UTF-8"?>
<xsl:stylesheet version="1.0"
xmlns:xsl="http://www.w3.org/1999/XSL/Transform">

<xsl:output method="html" indent="no" encoding="UTF-8"/>

<xsl:template match="/">
<html>
<head>
  <meta charset="utf-8"/>
  <title>Math library graph</title>
  <link rel="stylesheet" href="http://code.jquery.com/ui/1.11.2/themes/smoothness/jquery-ui.css"/>
  <script src="http://code.jquery.com/jquery-1.10.2.js"></script>
  <script src="http://code.jquery.com/ui/1.11.2/jquery-ui.js"></script>
  <script type='text/javascript' src='http://cdn.mathjax.org/mathjax/latest/MathJax.js?config=TeX-AMS-MML_HTMLorMML-full'></script>
  <script src="tooltip.js"></script>
</head>
<body>
  <img src='table.png' usemap='#mathlib' />
  <xsl:apply-templates />

  <xsl:for-each select='map/area'>
    <div id='{@href}_tip' style='display: none'>
      <xsl:copy-of select="document('../table.xml')/graph/node[key=current()/@href]/attributed_text" />
    </div>
  </xsl:for-each>
</body>
</html>
</xsl:template>

<xsl:template match='@href'>
  <xsl:attribute name='graphkey'>
    <xsl:value-of select='.'/>
  </xsl:attribute>
  <xsl:attribute name='href'>
    <xsl:value-of select='.'/>.html</xsl:attribute>
    <!-- todo: point to file generated by htlatex -->
</xsl:template>

<xsl:template match='@*|node()'>
  <xsl:copy>
    <xsl:apply-templates select='@*|node()'/>
  </xsl:copy>
</xsl:template>
</xsl:stylesheet>
