<?xml version="1.0" encoding="UTF-8"?>
<xsl:stylesheet version="1.0"
xmlns:xsl="http://www.w3.org/1999/XSL/Transform">

<xsl:output method="text" indent="no" encoding="UTF-8"/>

<xsl:key name="type" match="node" use="object_type" />

<xsl:template match="/">
\documentclass{article}
\usepackage{amsmath,amssymb}
\usepackage{hyperref}

\title{Math library}
\begin{document}
\maketitle

\newcommand{\lt}{&lt;}
\newcommand{\gt}{&gt;}

\newcommand{\newsection}[4]
{\subsection{#2}\label{#1}
\ifdefined\Link \Link{}{#1}\EndLink \fi
\noindent\hyperref[index:graph]{Back to graph}

\ifdefined\HCode\HCode{#4}\fi

#3

\noindent\hyperref[index:graph]{Back to graph}}

\ifdefined\HCode
\section{Graph}\label{index:graph}

\Configure{Link}{area}{href=}{name=}{}
\HCode{&lt;img src="table.png" usemap="\#mathlib"&gt;
&lt;map id="mathlib" name="mathlib"&gt;}<xsl:for-each select="document('../table.map')/map/area">\Link[   shape="poly" 
    id="<xsl:value-of select="@id" />"
    title="<xsl:value-of select="@title" />"
    graphkey="<xsl:value-of select="@href" />"
    alt=""
    coords="<xsl:value-of select="@coords" />"]
    {<xsl:value-of select="@href" />}{}</xsl:for-each>
\Configure{Link}{a}{href=}{name=}{}
\HCode{&lt;/map&gt;}

<xsl:for-each select="document('../table.map')/map/area">
  \HCode{&lt;div id='<xsl:value-of select="@href" />_tip' style='display: none'&gt;}
  <xsl:value-of select="document('../table.xml')/graph/node[key=current()/@href]/attributed_text" />
\HCode{&lt;/div&gt;}
</xsl:for-each>
\fi

\section{Definitions}
<xsl:for-each select="key('type','Definition')">
  <xsl:sort select="object_name"/>
  \newsection{<xsl:value-of select="key"/>}
  {<xsl:value-of select="object_name"/>}
  {<xsl:value-of select="attributed_text"/>}
  {<xsl:if test="node_file != ''"><img src="res/{node_file}" /></xsl:if>}
</xsl:for-each>

\section{Theorems}
<xsl:for-each select="key('type','Theorem')">
  <xsl:sort select="object_name"/>
  \newsection{<xsl:value-of select="key"/>}
  {<xsl:value-of select="object_name"/>}
  {<xsl:value-of select="attributed_text"/>}
  {<xsl:if test="node_file != ''"><img src="res/{node_file}" /></xsl:if>}
</xsl:for-each>

\section{Proofs}
<xsl:for-each select="key('type','Proof')">
  <xsl:sort select="object_name"/>
  \newsection{<xsl:value-of select="key"/>}
  {<xsl:value-of select="object_name"/>}
  {<xsl:value-of select="attributed_text"/>}
  {<xsl:if test="node_file != ''"><img src="res/{node_file}" /></xsl:if>}
</xsl:for-each>

\end{document}
</xsl:template>

<xsl:template match='@href'>
  <xsl:attribute name='graphkey'>
    <xsl:value-of select='.'/>
  </xsl:attribute>
  <xsl:attribute name='href'>
    <xsl:value-of select='.'/>.html</xsl:attribute>
    <!-- todo: point to file generated by htlatex -->
</xsl:template>

<xsl:template match='@*|node()'>
  <xsl:copy>
    <xsl:apply-templates select='@*|node()'/>
  </xsl:copy>
</xsl:template>

</xsl:stylesheet>
